import type { PortfolioProject } from "@/types/portfolio"

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "logistics-erp-platform",
    name: "Logistics ERP Platform",
    industry: "Logistics & Supply Chain",
    type: "Custom ERP System",
    outcome: "Unified logistics operations with real-time control across 4 regions.",
    image: "/images/portfolio/logistics.jpg",
    featured: true,
    metrics: [
      { value: "98% ", label: "On-Time Shipments" },
      { value: "3x ", label: "Faster Dispatch Coordination" },
      { value: "4 ", label: "Regions Unified" },
    ],
    caseStudyUrl: "/case-studies/national-fleet-operations-dashboard",
    liveUrl: "https://logistics-ops.example.com",
  },
  {
    slug: "fintech-compliance-engine",
    name: "FinTech Compliance Engine",
    industry: "FinTech",
    type: "Backend Infrastructure",
    outcome: "Automated KYC/AML checks for institutional crypto custody.",
    image: "/images/portfolio/fintech.jpg",
    featured: true,
    metrics: [
      { value: "99.9%", label: "Uptime Guaranteed" },
      { value: "<2s", label: "Verification Latency" },
      { value: "100%", label: "Audit Trail Integrity" },
    ],
    caseStudyUrl: "/case-studies/unified-legacy-operations-platform",
    liveUrl: "https://compliance.example.com",
  },
  {
    slug: "manufacturing-control-system",
    name: "Manufacturing Control System",
    industry: "Manufacturing",
    type: "Internal Tool",
    outcome: "Production visibility and inventory control across 4 plants.",
    image: "/images/portfolio/manufacturing.jpg",
    featured: false,
    metrics: [
      { value: "4 ", label: "Plants in a Single View" },
      { value: "25% ", label: "Unplanned Downtime Reduced" },
      { value: "Real-Time", label: "Production Telemetry" },
    ],
    caseStudyUrl: "/case-studies/manufacturing-erp-production-inventory",
    liveUrl: "https://manufacturing-ops.example.com",
  },
  {
    slug: "saas-crm-automation",
    name: "Sales CRM Automation",
    industry: "B2B SaaS",
    type: "Automation Infrastructure",
    outcome: "Reduced manual sales operations by 60% through AI orchestration.",
    image: "/images/portfolio/crm.jpg",
    featured: false,
    metrics: [
      { value: "60% ", label: "Manual Sales Ops Reduced" },
      { value: "30% ", label: "Faster Pipeline Updates" },
      { value: "24/7 ", label: "Automation Coverage" },
    ],
    caseStudyUrl: "/case-studies/unified-legacy-operations-platform",
    liveUrl: "https://revenue-automation.example.com",
  },
  {
    slug: "retail-inventory-ai",
    name: "Retail Inventory AI",
    industry: "Retail & E-commerce",
    type: "AI-Ready System",
    outcome: "Predictive restocking for multi-store retail operations.",
    image: "/images/portfolio/retail.jpg",
    featured: false,
    metrics: [
      { value: "15%", label: "Inventory Cost Reduction" },
      { value: "95%", label: "Stockout Prevention" },
      { value: "Automated", label: "Purchase Orders" },
    ],
    caseStudyUrl: "/case-studies/national-fleet-operations-dashboard",
    liveUrl: "https://inventory-ai.example.com",
  },
  {
    slug: "real-estate-platform",
    name: "PropTech Asset Manager",
    industry: "Real Estate",
    type: "Custom Business Platform",
    outcome: "Unified asset management and tenant communication portal.",
    image: "/images/portfolio/proptech.jpg",
    featured: false,
    metrics: [
      { value: "500+", label: "Assets Managed" },
      { value: "40%", label: "Faster Maintenance Response" },
      { value: "Integrated", label: "Payment Gateway" },
    ],
    caseStudyUrl: "/case-studies/manufacturing-erp-production-inventory",
    liveUrl: "https://proptech-manager.example.com",
  },
]
