import type { Testimonial } from "@/payload-types"

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "Elena Rodriguez",
    role: "Head of Operations, Global Logistics",
    content: "We moved from fragmented spreadsheets to a single, high-performance operational view. The system they built handles our multi-region dispatch with zero lag. It's the first time our data actually matches our operations.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "David Chen",
    role: "Founder, Fintech Scaleup",
    content: "The compliance engine they delivered didn't just meet our requirements—it gave us a competitive advantage. We can now verify institutional accounts in seconds rather than hours, with a full immutable audit trail.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Sarah Jenkins",
    role: "CTO, PropTech Group",
    content: "They understand that software is about business leverage, not just code. The architecture they implemented for our asset management platform has scaled perfectly as we've added 500+ properties.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Marcus Thorne",
    role: "Manufacturing Director",
    content: "Production and procurement finally talk to each other. The custom ERP backbone removed our inventory stockouts completely. It's rare to find a team that understands the factory floor as well as they do.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Nadia Osei",
    role: "COO, E-commerce Enterprise",
    content: "The AI-driven restocking system they built transformed our inventory costs. We've seen a 15% reduction in carrying costs without a single stockout. It's a structured system that delivers real ROI.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "James Wilson",
    role: "Chief of Staff, Series B Startup",
    content: "They translated our messy operational processes into a clean, automated workflow. Adoption across our sales team was immediate because the tools actually made their jobs easier, not harder.",
    rating: 5,
    type: "text",
    colSpan: 6,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
]
