export { default as CallToAction } from "./CallToAction"
export { ExpertiseMarquee } from "./ExpertiseMarquee"
export { default as HeroSection } from "./HeroSection"
export { default as IndustryImpactSection } from "./IndustryImpactSection"
export { default as IndustrySection } from "./IndustrySection"
export { default as Process } from "./Process"
export { default as Services } from "./Services"
export { default as TestimonialsSection } from "./testimonials/TestimonialsSection"
export { default as WhyXupyterSection } from "./WhyXupyterSection"
