import type { Metadata } from "next"
import localFont from "next/font/local"
import { Plus_Jakarta_Sans } from "next/font/google"
import Footer from "@/components/layout/Footer"
import "./globals.css"

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
})

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-plus-jakarta",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const theme = process.env.NEXT_PUBLIC_CURRENT_THEME ?? 'dark';

  return (
    <html lang="en" className={theme}>
      <body
        className={`${satoshi.variable} ${plusJakartaSans.variable} ${plusJakartaSans.className} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  )
}
