export { default as AboutHeader } from "./AboutHeader"
export { default as AboutContent } from "./AboutContent"
export { default as AboutTabs } from "./AboutTabs"
export { default as MapLegend } from "./MapLegend"
export { default as WorldMap } from "./WorldMap"
export * from "./AboutClient"
